### ISSUE TITLE
Fine model missing factor

### ISSUE THREAD

**Issue by Mar-ai** [EnexaProject/enexa-tensor-reasoning#4]
In https://github.com/EnexaProject/enexa-tensor-reasoning/blob/version1/examples/accounting/fine_product_taxrate_account.py#L46 the facts are removed before weight calibration; but they should still be included in the final [fine model](https://github.com/EnexaProject/enexa-tensor-reasoning/blob/version1/examples/accounting/assets/fine_model.yaml). 

Specifically, this logical formula is missing: 
(imp_(and_TAX_RATE_19_PRODUCT_CLASS_SEA-CP_05)_ACCOUNT_Account_4605)

**Comment by algoessmann** [comment]
In that demo, only a single formula is learned, and correctly identified as a fact. You can learn more facts by rerunning the referenced script, or including a while loop as for the coarse model training.

**Comment by Mar-ai** [comment]
Not sure how to handle this. 

The original [likelihood_gradient.values](https://github.com/EnexaProject/enexa-tensor-reasoning/blob/version1/examples/accounting/fine_product_taxrate_account.py#L37) are 

```
[[[[[[-0.16666667 -0.16666667 -0.16666667 -0.16666667 -0.16666667]]]


   [[[ 0.08333333  0.08333333  0.08333333  0.08333333  0.08333333]]]


   [[[ 0.08333333  0.08333333  0.08333333  0.08333333  0.08333333]]]]]]
``` 


so if I do: 

```
learnedFormulas = dict()
threshold = 0.08
i = 0
while np.max(likelihood_gradient.values) > threshold:
    selMax = likelihood_gradient.get_argmax()
    learnedFormulas["fine_"+str(i)] = encoding.create_solution_expression(fine_architecture, selMax)["neur1"]
    i+=1
    likelihood_gradient[selMax] = -1*likelihood_gradient[selMax]
    print(i)
    print(likelihood_gradient.values)
    print("---------------")

fineModel.include(knowledge.HybridKnowledgeBase(weightedFormulas={
    **{key: learnedFormulas[key]+[0] for key in learnedFormulas}
}))

weightEstimator = knowledge.WeightEstimator(fineModel)
weightEstimator.get_satisfaction_dict(empDist)
weightEstimator.fact_check()

# without 
# weightEstimator.calibrate_weights(10)

```
I switched off `weightEstimator.calibrate_weights(10)` because this takes very long (why is that?) and because, at this point, I mainly wanted to see all the facts. 
The resulting fine model then has three correct and two incorrect facts: (full fine model below) 

- correct: fine_1, fine_2, fine_9

- incorrect: fine_3, fine_8


Is it possible that the likelihood_gradient.values for the fine scenario are not correct? 
When using tnreason 1.0.1  on the same data this array is like so, so much more than just two values: 

``` 
array([[[[[[ 0.06666667, -0.1       , -0.1       ,  0.06666667,
            -0.1       ]]],


         [[[ 0.02083333,  0.1875    ,  0.1875    , -0.14583333,
             0.02083333]]],


         [[[-0.12083333,  0.04583333,  0.04583333, -0.12083333,
             0.2125    ]]]]]])
```





fine model: 
```
categoricalConstraints:
  account:
  - ACCOUNT_Account_3300
  - ACCOUNT_Account_3400
  - ACCOUNT_Account_4605
  product:
  - PRODUCT_CLASS_SEA-CP_01
  - PRODUCT_CLASS_SEA-CP_02
  - PRODUCT_CLASS_SEA-CP_03
  - PRODUCT_CLASS_SEA-CP_04
  - PRODUCT_CLASS_SEA-CP_05
  tax:
  - TAX_RATE_19
  - TAX_RATE_7
evidence: {}
facts:
  coarse_0:
  - imp
  - TAX_RATE_7
  - ACCOUNT_Account_3300
  fine_0:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_01
  - ACCOUNT_Account_3400
  fine_1:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_02
  - ACCOUNT_Account_3400
  fine_2:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_03
  - ACCOUNT_Account_3400
  fine_3:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_04
  - ACCOUNT_Account_3400
  fine_8:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_04
  - ACCOUNT_Account_4605
  fine_9:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_05
  - ACCOUNT_Account_4605
weightedFormulas:
  coarse_1:
  - imp
  - TAX_RATE_19
  - ACCOUNT_Account_3400
  - 1.6094379124341007
  fine_4:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_05
  - ACCOUNT_Account_3400
  - 0.0
  fine_5:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_01
  - ACCOUNT_Account_4605
  - 0.0
  fine_6:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_02
  - ACCOUNT_Account_4605
  - 0.0
  fine_7:
  - imp
  - - and
    - TAX_RATE_19
    - PRODUCT_CLASS_SEA-CP_03
  - ACCOUNT_Account_4605
  - 0.0
```
